WebApplication1/Controllers/AuthCallbackController.cs
using Dropbox.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SecureCloud.Models;
using Microsoft.AspNet.Identity;

namespace SecureCloud.Controllers
{
    [Authorize]
    public class AuthCallbackController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Redirect(string code, string state)
        {
            var Response = await DropBox.Handle(code, state);

            db.TokenStores.Add(new TokenStore
            {
                ID = User.Identity.GetUserId(),
                Token = Response.AccessToken,
                UId = Response.Uid
            });

            await db.SaveChangesAsync();

            return RedirectToAction("Index", "Files");
        }

        public ActionResult Connect()
        {
            return Redirect(DropBox.Connect());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }

}

WebApplication1/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecureCloud.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using System.Text;



namespace SecureCloud.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Files
        public async Task<ActionResult> Index()
        {
            var Token = await db.TokenStores.FindAsync(User.Identity.GetUserId());

            if (Token == null)
            {
                return RedirectToAction("Connect");
            }

            var ID = User.Identity.GetUserId();

            return View((await db.UserFileStores.Include(x => x.FileStore).Where(x => x.User.Id == ID).ToListAsync()).OrderByDescending(x=>x.FileStore.CreatedAt));
        }

        public ActionResult Connect()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Upload(IEnumerable<HttpPostedFileBase> Files)
        {
            var file = Files.FirstOrDefault();

            try
            {
                var TokenStore = await db.TokenStores.FindAsync(User.Identity.GetUserId());

                if (TokenStore == null)
                {
                    throw new Exception("AccessTokenNotFound");
                }

                var ID = User.Identity.GetUserId();
                var Key = KeyGenerator.CreateKey();
                var ApplicationUser = await db.Users.Where(x => x.Id == ID).FirstOrDefaultAsync();

                if (ApplicationUser != null)
                {
                    var FileStore = new FileStore
                    {
                        ID = Guid.NewGuid().ToString(),
                        Name = file.FileName,
                        Size = file.ContentLength,
                        Type = file.ContentType,
                        CreatedAt = DateTime.Now
                    };

                    var UserFileStore = new UserFileStore
                    {
                        ID = Guid.NewGuid().ToString(),
                        FileStore = FileStore,
                        Key = Key,
                        User = ApplicationUser
                    };

                    using (var binaryReader = new BinaryReader(file.InputStream))
                    {
                        if (await DropBox.Upload(TokenStore.Token, UserFileStore.ID, Crypto.AES_Encrypt(binaryReader.ReadBytes(Request.Files[0].ContentLength), Crypto.GetBytes(Key))))
                        {
                            db.FileStores.Add(FileStore);
                            db.UserFileStores.Add(UserFileStore);
                            await db.SaveChangesAsync();

                            return Json(new { name = file.FileName });
                        }
                    }
                }
                else
                {
                    return Json(new { status = "NotFound", name = file.FileName });
                }


            }
            catch (Exception ex)
            {
                return Json(new { status = ex.Message, name = file.FileName });
            }

            return Json(new { status = "ProcessFailed", name = file.FileName });
        }

        // GET: Files/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ID = User.Identity.GetUserId();

            UserFileStore userFileStore = await db.UserFileStores.Include(x => x.FileStore).Where(x => x.ID == id && x.User.Id == ID).FirstOrDefaultAsync();
            if (userFileStore == null)
            {
                return HttpNotFound();
            }
            return View(userFileStore);
        }

        // GET: Files/Details/5
        public async Task<ActionResult> Share(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ID = User.Identity.GetUserId();

            UserFileStore userFileStore = await db.UserFileStores.Include(x => x.FileStore).Where(x => x.ID == id && x.User.Id == ID).FirstOrDefaultAsync();
            if (userFileStore == null)
            {
                return HttpNotFound();
            }

            return View(new ShareUserFileViewModel
            {
                ID = userFileStore.ID,
                Email = "",
                UserFileStore = userFileStore
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Share([Bind(Include = "")] ShareUserFileViewModel shareUserFileViewModel)
        {
            var ID = User.Identity.GetUserId();

            UserFileStore userFileStore = await db.UserFileStores.Include(x => x.FileStore).Where(x => x.ID == shareUserFileViewModel.ID && x.User.Id == ID).FirstOrDefaultAsync();
            if (userFileStore == null)
            {
                return HttpNotFound();
            }

            try
            {

                if (ModelState.IsValid)
                {
                    var ApplicationUser = await db.Users.Where(x => x.Email == shareUserFileViewModel.Email).FirstOrDefaultAsync();

                    if (ApplicationUser == null)
                    {
                        ModelState.AddModelError("Email", "Specified user not found.");
                    }
                    else
                    {
                        if (ApplicationUser.Id != ID)
                        {
                            var KeyPairs = await db.UserKeyPairStores.Where(x => x.ID == ApplicationUser.Id || x.ID == ID).ToListAsync();

                            if (KeyPairs.Count() > 1)
                            {

                                var ShareKeyPair = KeyPairs.Where(x => x.ID == ApplicationUser.Id).FirstOrDefault();
                                var FileStore = await db.FileStores.FindAsync(userFileStore.FileStore.ID);                               

                                db.ShareFile.Add(new ShareFile
                                {
                                    ID = Guid.NewGuid().ToString(),
                                    FileStore = FileStore,
                                    Key = Convert.ToBase64String(Crypto.RSA_Encrypt(ShareKeyPair.PublicKey, Crypto.GetBytes(userFileStore.Key))),
                                    User = ApplicationUser,
                                    CreatedAt = DateTime.Now
                                });

                                await db.SaveChangesAsync();

                                return RedirectToAction("Index");

                            }
                            else
                            {
                                ModelState.AddModelError("Email", "Security key pairs not found.");
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("Email", "Cannot share the file to the same user.");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Email", ex.Message);
            }

            return View(new ShareUserFileViewModel
            {
                ID = userFileStore.ID,
                Email = shareUserFileViewModel.Email,
                UserFileStore = userFileStore
            });
        }

        // GET: Files/Details/5
        public async Task<ActionResult> Download(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ID = User.Identity.GetUserId();

            UserFileStore userFileStore = await db.UserFileStores.Include(x => x.FileStore).Where(x => x.ID == id && x.User.Id == ID).FirstOrDefaultAsync();
            if (userFileStore == null)
            {
                return HttpNotFound();
            }

            var TokenStore = await db.TokenStores.FindAsync(User.Identity.GetUserId());

            if (TokenStore == null)
            {
                return HttpNotFound();
            }

            var FileData = await DropBox.Download(TokenStore.Token, userFileStore.ID);

            if (FileData == null)
            {
                return HttpNotFound();
            }

            var Content = new System.Net.Mime.ContentDisposition
            {
                FileName = System.Text.RegularExpressions.Regex.Replace(userFileStore.FileStore.Name, @"\s+", "_"),
                Inline = false,
            };

            Response.AppendHeader("Content-Disposition", Content.ToString());
            return File(Crypto.AES_Decrypt(FileData, Encoding.UTF8.GetBytes(userFileStore.Key)), userFileStore.FileStore.Type);
        }

        // GET: Files/Create
        public async Task<ActionResult> Create()
        {
            var Token = await db.TokenStores.FindAsync(User.Identity.GetUserId());

            if (Token == null)
            {
                return RedirectToAction("Connect");
            }

            return View();
        }


        // GET: Files/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var ID = User.Identity.GetUserId();

            UserFileStore userFileStore = await db.UserFileStores.Include(x => x.FileStore).Where(x => x.ID == id && x.User.Id == ID).FirstOrDefaultAsync();
            if (userFileStore == null)
            {

WebApplication1/Views/Files/Connect.cshtml
@{
    ViewBag.Title = "Connect";
}

<div class="jumbotron">
    <h1>Connect with Dropbox</h1>
    <p class="lead">Connect your application with the dropbox cloud stroage to save your file and datas securly. Dropbox is a service that keeps your files safe, synced, and easy to share. Bring your photos, docs, and videos anywhere and never lose a file again.</p>
    <p><a href="@Url.Action("Connect", "AuthCallback")" class="btn btn-success btn-lg">Take me to Dropbox &raquo;</a></p>
</div>

WebApplication1/Views/Files/Create.cshtml
@model SecureCloud.Models.UserFileStore

@{
    ViewBag.Title = "Create";
}

<h2>Upload Files to Cloud</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Select files to upload</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                <input id="fileupload" type="file" name="files" multiple="multiple" />
            </div>
        </div>

        <div class="progress" id="progress" style="display:none">
            <div class="bar progress-bar progress-bar-striped active" role="progressbar" style="width: 0%">

            </div>
        </div>

        <ul class="list-group" id="files"></ul>

        <ul class="list-group" id="uploaded"></ul>

        <div class="form-group">
            <div class="col-md-10">
                <input type="button" value="Upload" id="upload" disabled="disabled" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(function () {

            var list = [];

            $("#upload").off('click').on('click', function () {
                $("#upload").attr("disabled", "disabled");
                $.each(list, function (i, data) {
                    data.submit();
                });
            });

            $('#fileupload').fileupload({
                autoUpload: false,
                sequentialUploads: true,
                dataType: 'json',
                url: '@Url.Action("Upload")',
                done: function (e, data) {
                    if (data.result.status) {                        
                        $("#uploaded").append('<li class="list-group-item list-group-item-danger"><span class="badge">Failed</span>' + data.result.name + '</li>');
                    } else {
                        $("#uploaded").append('<li class="list-group-item"><span class="badge">Uploaded</span>' + data.result.name + '</li>');
                    }

                    for (var i = 0; i < list.length; i++) {                       
                        if (list[i].files[0].name == data.result.name) {
                            list.splice(i, 1);
                        }
                    }

                    if (list.length == 0) {
                        $("#progress").fadeOut(100);
                        $("#upload").val("Uploaded");
                    }
                },
                fail: function (e) {
                    console.error(e);
                },
                start: function () {
                    $("#progress").fadeIn(100);

                },
                progress: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);

                    if (progress >= 100) {
                        $("#files > li").first().remove();
                    }
                },
                progressall: function (e, data) {
                    var progress = parseInt(data.loaded / data.total * 100, 10);
                    $("#upload").val("Uploading... " + progress + '%');
                    $('#progress .bar').css(
                        'width',
                        progress + '%'
                    );

                    if (progress >= 100) {
                        $("#upload").val("Processing..");
                    }
                },
                change: function (e, data) {
                    $("#files").html("");
                    $("#uploaded").html("");

                    $.each(data.files, function (i, file) {
                        $("#files").append('<li class="list-group-item"><span class="badge">Waiting</span><span>' + file.name + '</span></li>')
                    });

                    $("#upload").val("Upload");
                    $("#upload").removeAttr("disabled");
                },
                add: function (e, data) {
                    list.push(data);
                }

            });
        });
    </script>
}

WebApplication1/Views/Files/Delete.cshtml
@model SecureCloud.Models.UserFileStore

@{
    ViewBag.Title = "Delete";
}

<h2>My Drive</h2>

<h3>Are you sure you want to delete this?</h3>
<div>

    <table class="table table-bordered detail-table">
        <tr>
            <td>Name</td>
            <td>@Model.FileStore.Name</td>
        </tr>

        <tr>
            <td>Size</td>
            <td>@Model.FileStore.SizeText</td>
        </tr>
    </table>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <p>
                <input type="submit" value="Yes, Delete" class="btn btn-danger" />
            </p>
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/Views/Files/Details.cshtml
@model SecureCloud.Models.UserFileStore

@{
    ViewBag.Title = "Details";
}

<h2>My Drive</h2>

<div>
    <h4>File Information</h4>

    <table class="table table-bordered detail-table">
        <tr>
            <td>Name</td>
            <td>@Model.FileStore.Name</td>
        </tr>
        <tr>
            <td>Type</td>
            <td>@Model.FileStore.Type</td>
        </tr>
        <tr>
            <td>Created</td>
            <td>@Model.FileStore.CreatedAt.ToString("dd MMM, yyyy")</td>
        </tr>
        <tr>
            <td>Size</td>
            <td>@Model.FileStore.SizeText</td>
        </tr>
    </table>
    <p>
        <div>
            <a href="@Url.Action("Share", new { id = Model.ID })" class="btn btn-sm btn-info">
                <i class="glyphicon glyphicon-share"></i> Share
            </a>
            <a href="@Url.Action("Delete", new { id = Model.ID })" class="btn btn-sm btn-danger">
                <i class="glyphicon glyphicon-trash"></i> Delete
            </a>
        </div>
    </p>
</div>
<p>
    
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication1/Views/Files/Edit.cshtml
@model SecureCloud.Models.UserFileStore

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserFileStore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication1/Views/Files/Index.cshtml
@model IEnumerable<SecureCloud.Models.UserFileStore>

@{
    ViewBag.Title = "Index";
}

<h2>My Drive</h2>

<p style="text-align:right">
    <a href="@Url.Action("Create")" class="btn btn-sm btn-primary">
        <i class="glyphicon glyphicon-upload"></i> Upload Files
    </a>
</p>
<table class="table">
    <tr>
        <th>
            File
        </th>

        <th>
            Type
        </th>
        <th>
            Created
        </th>
        <th style="text-align: right">
            Size
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.FileStore.Name, "Details", new { id = item.ID })
            </td>

            <td>
                @item.FileStore.Type
            </td>
            <td>
                @item.FileStore.CreatedAt.ToString("dd MMM, yyyy")
            </td>
            <td style="text-align: right">
                @item.FileStore.SizeText
            </td>
            <td style="text-align:right">
                <a href="@Url.Action("Share", new { id = item.ID })" class="btn btn-sm btn-info">
                    <i class="glyphicon glyphicon-share"></i> Share
                </a>
                <a href="@Url.Action("Download", new { id = item.ID })" class="btn btn-sm btn-success">
                    <i class="glyphicon glyphicon-download-alt"></i> Download
                </a>
            </td>
        </tr>
    }

</table>

WebApplication1/Views/Files/Share.cshtml
@model SecureCloud.Models.ShareUserFileViewModel

@{
    ViewBag.Title = "Share";
}

<h2>My Drive</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Share File</h4>

        <p>
            <table class="table table-bordered detail-table">
                <tr>
                    <td>Name</td>
                    <td>@Model.UserFileStore.FileStore.Name</td>
                </tr>

                <tr>
                    <td>Size</td>
                    <td>@Model.UserFileStore.FileStore.SizeText</td>
                </tr>
            </table>
        </p>


        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Share" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}