WebApplication1/Controllers/DriveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecureCloud.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace SecureCloud.Controllers
{
    [Authorize]
    public class DriveController : Controller
    {
        // GET: Drive

        private ApplicationDbContext db = new ApplicationDbContext();

        public async Task<ActionResult> Index()
        {
            var ID = User.Identity.GetUserId();

            var Token = await db.TokenStores.FindAsync(ID);

            if (Token == null)
            {
                return RedirectToAction("Connect", "Files");
            }
            
            return View(await DropBox.Info(Token.Token));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SecureCloud.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace SecureCloud.Controllers
{
    [Authorize]
    public class SharedController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Shared
        public async Task<ActionResult> Index()
        {
            var ID = User.Identity.GetUserId();
            var FileStores = await db.UserFileStores.Where(x => x.User.Id == ID).Select(x => x.FileStore.ID).ToListAsync();
            var Shared = await db.ShareFile.Include(x => x.FileStore).Include(x => x.User).Where(x => FileStores.Contains(x.FileStore.ID)).ToListAsync();

            return View(Shared);
        }

        public async Task<ActionResult> Revoke(string id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var Shared = await db.ShareFile.FindAsync(id);

            db.ShareFile.Remove(Shared);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/Index.cshtml
@model IEnumerable<SecureCloud.Models.ShareFile>

@{
    ViewBag.Title = "Index";
}

<h2>Shared</h2>


<table class="table">
    <tr>
        <th>
            File
        </th>

        <th>
            Type
        </th>
        <th>
            Shared On
        </th>
        <th>
            Shared With
        </th>
        <th style="text-align: right">
            Size
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.FileStore.Name
            </td>
            <td>
                @item.FileStore.Type
            </td>
            <td>
                @item.CreatedAt.ToString("dd MMM, yyyy")
            </td>
            <td>
                @item.User.UserName
            </td>
            <td style="text-align: right">
                @item.FileStore.SizeText
            </td>
            <td style="text-align:right">
                <a href="@Url.Action("Revoke", new { id = item.ID })" class="btn btn-sm btn-danger">
                    <i class="glyphicon glyphicon-ban-circle"></i> Revoke
                </a>
            </td>
        </tr>
    }

</table>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Secure Cloud</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Secure Cloud", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("My Drive", "Index", "Files")</li>
                    <li>@Html.ActionLink("Incoming", "Index", "Incoming")</li> 
                    <li>@Html.ActionLink("Shared Files", "Index", "Shared")</li> 
                    <li>@Html.ActionLink("Accounts", "Index", "Drive")</li> 
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Secure Cloud</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>